sudo: false

# TODO: Restructure this so that multiple traits and platforms can be built during one run
# because ImageBuilders can be quite large (rt305x is 1.5 GB) this will increase efficiency

env:
  global:
#    - TRAIT=tor-router-glinet
  matrix:
    - TRAIT=tor-router-dual-eth PLATFORM="" IMAGEBUILDER_URL="https://downloads.openwrt.org/chaos_calmer/15.05/x86/64/OpenWrt-ImageBuilder-15.05-x86-64.Linux-x86_64.tar.bz2"
    - TRAIT=tor-router-glinet PLATFORM=GLINET IMAGEBUILDER_URL="https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/OpenWrt-ImageBuilder-ar71xx-generic.Linux-x86_64.tar.bz2"
    - PREBUILD=lib/prebuild/tlwr-16m.sh TRAIT=tor-router PLATFORM=TLWR703 IMAGEBUILDER_URL="https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/OpenWrt-ImageBuilder-ar71xx-generic.Linux-x86_64.tar.bz2"
    # trunk tor router
    - TRAIT=tor-router-dual-eth PLATFORM="" IMAGEBUILDER_URL="https://downloads.openwrt.org/snapshots/trunk/x86/64/OpenWrt-ImageBuilder-x86-64.Linux-x86_64.tar.bz2"

script:
  - git clone https://github.com/krebscode/minikrebs.git
  - cd minikrebs/
  - ./prepare $TRAIT
  # TODO: generalize PREBUILD for use without travis
  - test ! -e "$PREBUILD" || ( cp "$PREBUILD" builder/ && (cd builder/ && sh $(basename $PREBUILD)) && echo "prebuild script successful" )
  - ./builder/init
  - ls -lh ./builder/bin/*/*squashfs*
  - find ./builder/bin -type f -regex ".*squashfs.*\.\(bin\|img\)" -regextype posix-egrep -print0 | xargs -0 -n1 bash -e bintray.sh
